export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS"
export const GET_POINTS = "GET_POINTS"
export const SET_SUITABLE_POINTS = "SET_SUITABLE_POINTS"
export const GET_BEST_SUITABLE_POINTS = "GET_BEST_SUITABLE_POINTS"
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE"